spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE.HOST}:${DATABASE.PORT}/${DATABASE.NAME}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC+9&useSSL=false
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}