spring:
  profiles: totalTest
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        use_sql_comments: true


datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}

#open-in-view 사용자 요청 시작 후 Session 계속 열어두는 것


app:
  datetime-format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor.sql.BasicBinder: TRACE
        descriptor.sql: TRACE
    com.tera.pretest: INFO