spring:
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: test, test-secret

server:
  port: 8080

app:
  datetime-format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"


logging:
  level:
    root: INFO
    com.tera.pretest: TRACE

