spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/pretest01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC+9&useSSL=false
    username: pretest
    password: 20240524